apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: log-test
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluent-bit-read
rules:
- apiGroups: [ "" ]
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: log-test

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: log-test
  labels:
    k8s-app: fluent-bit
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output.conf

  output.conf: |
    [OUTPUT]
        Name              grafana-loki
        Url               ${LOKI_URL}
        Match             kube.var.log.containers.logapp*.*
        Labels            {job="log-app"}
        LabelKeys         date,statusCode,duration,message,stream
        RemoveKeys        date,statusCode,duration,message,stream

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            cri
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   Off
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Trim      On
        Keep_Log            Off
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Annotations         Off
        Labels              On

    [FILTER]
        Name          nest
        Match         kube.*
        Operation     lift
        Nested_under  kubernetes
        Add_prefix    kubernetes_

    [FILTER]
        Name          nest
        Match         kube.*
        Operation     lift
        Nested_under  kubernetes_labels
        Add_prefix    kubernetes_labels_

  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    time
        Time_Format %d/%b/%Y:%H:%M:%S %z
        Time_Keep   Off

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S

    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep Off

---

apiVersion: v1
kind: Pod
metadata:
  name: fluent-bit
  namespace: log-test
  labels:
    app: fluent-bit
spec:
    priorityClassName: system-node-critical
    serviceAccountName: fluent-bit
    terminationGracePeriodSeconds: 10

    securityContext:
      seccompProfile:
        type: RuntimeDefault

    containers:
    - name: fluent-bit
      imagePullPolicy: Always
      image: grafana/fluent-bit-plugin-loki:latest
      env:
        - name: LOKI_URL
          valueFrom:
            secretKeyRef:
              name: fluent-bit-secrets
              key: LokiUrl
      ports:
        - containerPort: 2020
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
      volumeMounts:
      - name: varlog
        mountPath: /var/log

      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true

      - name: fluent-bit-config
        mountPath: /fluent-bit/etc/

    volumes:
    - name: varlog
      hostPath:
        path: /var/log

    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers

    - name: fluent-bit-config
      configMap:
        name: fluent-bit-config
