kind: Simple
apiVersion: k3d.io/v1alpha3
servers: 1
kubeAPI:
  hostIP: 0.0.0.0
  hostPort: "6443"
network: k3d
options:
  k3d:
    wait: true
    timeout: 60s
    disableLoadbalancer: true
    disableImageVolume: false
    disableRollback: false
  k3s:
    extraArgs:
    - arg: --tls-san=127.0.0.1
      nodeFilters:
      - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
  runtime: {}
